#!/bin/bash

## https://gist.github.com/1336585

juju-log "Installing OpenJDK"
apt-get install -y openjdk-6-jre

juju-log "Add minecraft init script" 
cp opt/minecraft /etc/init.d/minecraft && chmod 0755 /etc/init.d/minecraft

juju-log "Downloading Minecraft"
mkdir -p /opt/minecraft/
wget "https://s3.amazonaws.com/MinecraftDownload/launcher/minecraft_server.jar" -O /opt/minecraft/minecraft_server.jar

juju-log "Setting up initial Minecraft directory structure"
/etc/init.d/minecraft start
sleep 60
/etc/init.d/minecraft stop

juju-log "Expose the Minecraft port"
open-port 25565
